import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent any
  environment {
  	Servidor1= "C:\\inetpub\\www_api\\Arquetipo.API\\"
  	ProyectoApi= "Arquetipo.API\\Arquetipo.API.csproj"
  	ProyectoTesting="Arquetipo.Test\\Arquetipo.Test.csproj"
    dotnet ='C:\\Program Files (x86)\\dotnet\\'
    
  }
  stages {
	stage('Restore packages'){
	   steps{
	      bat "dotnet restore"
	     }
	  }
	stage('Clean'){
	    steps{
		bat "dotnet clean"
	     }
	   }	
	stage('Build'){
	   steps{
	      bat "dotnet build %ProyectoApi% --configuration Release"
	    }
	 }
	/*stage('Test: Unit Test'){
	   steps {
	     bat "dotnet test %ProyectoTesting%"
	     }
	  }*/
	stage('Publish'){
	     steps{
	       bat "dotnet publish %ProyectoApi% -o Publish "
	     }
	}
	stage('Publish IIS'){
	     steps{
	       bat "echo.>%Servidor1%offline.html"
	       bat "Xcopy Publish %Servidor1% /E /H /C /I"
	       bat "del %Servidor1%offline.html"
	     }
	}	
	
  }
  post {
      always {          
          //deleteDir()
           bat "echo 'fase always'"
      }
      success {
            bat "echo 'Termino ok'"
        }

      failure {
            bat "echo 'fase failure'"
      }
      
  }
}  

