import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent any
  environment {
  	ProyectoApi= "Arquetipo.API\\Arquetipo.API.csproj"
  	ProyectoTesting="Arquetipo.Test\\Arquetipo.Test.csproj"
    dotnet ='C:\\Program Files (x86)\\dotnet\\'
    
  }
  stages {
	stage('Restore packages'){
	   steps{
	      bat "dotnet restore"
	     }
	  }
	stage('Clean'){
	    steps{
		bat "dotnet clean"
	     }
	   }	
	stage('Build'){
	   steps{
	      bat "dotnet build %ProyectoApi% --configuration Release"
	    }
	 }
	stage('Test: Unit Test'){
	   steps {
	     bat "dotnet test %ProyectoTesting%"
	     }
	  }
	stage('Publish'){
	     steps{
	       bat "dotnet publish %ProyectoApi% "
	     }
	}	      
  }
  post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'Termino ok'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }
}  

